[phases.setup]
nixPkgs = ["nodejs-18_x", "yarn"]

[phases.install]
cmds = [
  "cd src/frontend",
  "yarn install --frozen-lockfile"
]

[phases.build]
cmds = [
  "cd src/frontend",
  "yarn build"
]

[start]
cmd = "cd src/frontend && yarn start"

