[build]
builder = "NIXPACKS"
buildCommand = "cd src/frontend && yarn install && yarn build"

[deploy]
startCommand = "cd src/frontend && yarn start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

