[build]
builder = "NIXPACKS"
buildCommand = "cd src/backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd src/backend && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn impress.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/v1.0/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

