# Generated by Django 5.2.7 on 2025-10-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_databasemodel_databaseproperty_databaserow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaserow',
            name='properties',
            field=models.JSONField(blank=True, default=dict, help_text='Property values as JSON (property_id -> value)', verbose_name='properties'),
        ),
    ]
